# Generated by Django 5.2.3 on 2025-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_student_school_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='branch',
            field=models.CharField(blank=True, default='perm site', max_length=255, null=True),
        ),
    ]
