# Generated by Django 5.2.3 on 2025-06-29 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_teachers_remove_courses_student_alter_student_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
