# Generated by Django 5.2.3 on 2025-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_teacher_courses_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teachers',
            name='course',
            field=models.ManyToManyField(related_name='course', to='product.courses'),
        ),
    ]
