# Generated by Django 5.2.3 on 2025-06-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_courses_teachers_teachers_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='course',
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='product.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='product.subjects'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
