# Generated by Django 5.2.3 on 2025-06-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_students_courses_remove_teachers_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=17),
        ),
    ]
