# Generated by Django 5.2.3 on 2025-06-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_student_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Student_table',
        ),
    ]
