# Generated by Django 5.2.3 on 2025-06-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_students_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
