# Generated by Django 5.2.3 on 2025-06-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_students_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='students', to='product.student'),
        ),
    ]
