# Generated by Django 5.2.3 on 2025-07-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_courses_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
    ]
