# Generated by Django 5.2.3 on 2025-07-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age', 'name']},
        ),
    ]
