# Generated by Django 5.2.3 on 2025-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'age']},
        ),
    ]
