# Generated by Django 5.2.3 on 2025-07-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_student_options_rename_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
