# Generated by Django 5.2.3 on 2025-07-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_student_bio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name')},
        ),
    ]
