# Generated by Django 5.2.3 on 2025-07-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
