# Generated by Django 5.2.3 on 2025-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
