# Generated by Django 5.2.3 on 2025-07-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='kajan', max_length=100),
        ),
    ]
